apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'my-service'
  delay:
    latency: '200ms'
    jitter: '50ms'
  direction: to
  duration: '3m'
