apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: production
spec:
  action: pod-kill
  mode: one
  duration: '5m'
  selector:
    labelSelectors:
      'app': 'my-service'
    namespaces:
      - 'production'
  scheduler:
    cron: '@every 60s'
