# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics,loggers
management.endpoint.health.show-details=always
management.endpoint.health.group.liveness.include=diskSpace,ping
management.endpoint.health.group.readiness.include=ping
