apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
    env: production
    version: 1.0.0
spec:
  type: LoadBalancer
  selector:
    app: my-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
